cocos/cocos-test-projects

- assets/cases/base.meta
- assets/cases/base/deprecated-testing.ts
- assets/cases/base/deprecated-testing.ts.meta
- assets/cases/base/deprecated.scene
- assets/cases/base/deprecated.scene.meta
关联引擎PR  https://github.com/cocos-creator/engine/pull/5005
> add deprecated testing cases

- assets/cases/tween.meta
- assets/cases/tween/tween-test.ts
- assets/cases/tween/tween-test.ts.meta
- assets/cases/tween/tween.scene
- assets/cases/tween/tween.scene.meta
需要等这个PR通过 https://github.com/cocos-creator/engine/pull/5128
> add tween basic testing

- assets/cases/rendering/planar-shadow.scene
- assets/cases/rendering/planar-shadow.scene.meta
- assets/cases/rendering/sort.scene
- assets/cases/rendering/sort.scene.meta
white screen scenes fix，add camera script
> white screen scenes fix

- assets/cases/TestList/ListItem.prefab
- assets/cases/TestList/listitem.ts
RE: https://github.com/cocos-creator/3d-tasks/issues/1329
> scenelist prefab fix

- assets/cases/physics/VelocitySetup.ts
- assets/cases/physics/VelocitySetup.ts.meta
- assets/cases/physics/a-start.scene
- assets/cases/physics/cannon/physic-material.scene
- assets/cases/physics/cannon/physic-material.scene.meta
- assets/cases/physics/cannon/scripts/PhysicMaterialSetup.ts
- assets/cases/physics/cannon/scripts/PhysicMaterialSetup.ts.meta
- assets/cases/physics/测试说明.md.meta
需要等待这个 PR 合并
https://github.com/cocos-creator/engine/pull/5308
> add physic material test case

- assets/cases/ui/04.widget/widget-preformance.ts
RE : https://github.com/cocos-creator/3d-tasks/issues/1485
> fixed widget-performance bug

- assets/cases/TestList/backbutton.ts
- assets/cases/TestList/listitem.ts
- assets/cases/TestList/scenelist.ts
TestList scene scroll to the position before enter the scene
> TestList scroll to add

- assets/cases/TestList/scenelist.ts
- assets/cases/ui/04.widget/advance-widget.scene
- assets/cases/ui/04.widget/widget-percentage.scene
- assets/cases/ui/04.widget/widget-percentage.scene.meta
widget-percentage case add
RE:https://github.com/cocos-creator/3d-tasks/issues/1595
> widget-percentage add

- assets/cases/scripting/asset_loading/LoadRes.meta
- assets/cases/scripting/asset_loading/LoadRes.scene
- assets/cases/scripting/asset_loading/LoadRes.scene.meta
- assets/cases/scripting/asset_loading/LoadRes/LoadRes_example.ts
- assets/cases/scripting/asset_loading/LoadRes/LoadRes_example.ts.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/1769
> AssetLoading scene update

- assets/cases/TestList/TestList.scene
- assets/cases/TestList/TestList.scene.meta
RE： https://github.com/cocos-creator/3d-tasks/issues/1778
> TestList scrollview start change

- assets/cases/ui/18.canvas.meta
- assets/cases/ui/18.canvas/click-event.ts
- assets/cases/ui/18.canvas/click-event.ts.meta
- assets/cases/ui/18.canvas/multi-canvas.scene
- assets/cases/ui/18.canvas/multi-canvas.scene.meta
add in version 1.0.2
RE: https://github.com/cocos-creator/3d-tasks/issues/1120
> multi-canvas test add

- assets/cases/ui/01.sprite/sprite-grayscale.scene
- assets/cases/ui/01.sprite/sprite-grayscale.scene.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/1740
RE: https://github.com/cocos-creator/3d-tasks/issues/1659
> sprite-grayscale case add

- assets/cases/physics/builtin/group-mask-builtin.scene
- assets/cases/physics/builtin/group-mask-builtin.scene.meta
- assets/cases/physics/builtin/trigger-builtin.scene
- assets/cases/physics/builtin/trigger-builtin.scene.meta
- assets/cases/physics/cannon/collision.scene
- assets/cases/physics/cannon/collision.scene.meta
- assets/cases/physics/cannon/constant-force.scene
- assets/cases/physics/cannon/constant-force.scene.meta
- assets/cases/physics/cannon/force-impluse.scene
- assets/cases/physics/cannon/force-impluse.scene.meta
- assets/cases/physics/cannon/group-mask.scene
- assets/cases/physics/cannon/group-mask.scene.meta
- assets/cases/physics/cannon/physic-material.scene
- assets/cases/physics/cannon/physic-material.scene.meta
- assets/cases/physics/cannon/trigger.scene
- assets/cases/physics/cannon/trigger.scene.meta
- assets/cases/physics/cannon/velocity.scene
- assets/cases/physics/cannon/velocity.scene.meta
- assets/cases/physics/prefabs/CanvasCheck.prefab
- assets/cases/physics/prefabs/CanvasCheck.prefab.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/1742
> physics test mask update

- assets/cases/material/material.scene
- assets/cases/material/material.scene.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/1746
> material scene UI update

- assets/cases/TestList/TestList.scene
- assets/cases/rendertexture/render-ui-to-model.scene
- assets/cases/rendertexture/render-ui-to-model.ts
- assets/cases/rendertexture/render-ui-to-spriteframe.scene
https://github.com/cocos-creator/3d-tasks/issues/1767
https://github.com/cocos-creator/3d-tasks/issues/1772
> fix ui test render err

- assets/cases/TestList/ListItem.prefab.meta
- assets/cases/TestList/backbutton.ts
- assets/cases/TestList/backbutton.ts.meta
- assets/cases/TestList/exitLeft.png.meta
- assets/cases/TestList/left.png.meta
- assets/cases/TestList/listitem.ts.meta
- assets/cases/TestList/panelBG.png.meta
- assets/cases/TestList/right.png.meta
- assets/cases/TestList/scenelist.ts.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/1755
> scene change update

- assets/cases/ui/05.layout/layout-scrollview.scene
Re: https://github.com/cocos-creator/3d-tasks/issues/1801
> layout-scrollview add tips

- assets/cases/ui/01.sprite/fill-sprite.scene
- assets/cases/ui/01.sprite/fill-sprite.ts
- assets/cases/ui/01.sprite/fill-sprite.ts.meta
- assets/cases/ui/01.sprite/simple.scene
- assets/cases/ui/04.widget/widget-percentage.scene
- assets/cases/ui/11.progress/progress.scene
- assets/cases/ui/11.progress/progress.ts
- assets/cases/ui/11.progress/progress.ts.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/1766
> 加了一部分测试例动态效果和tips

- assets/cases/ui/04.widget/SpritePrefab.prefab
- assets/cases/ui/04.widget/SpritePrefab.prefab.meta
- assets/cases/ui/04.widget/widget-destroy.scene
- assets/cases/ui/04.widget/widget-destroy.scene.meta
- assets/cases/ui/04.widget/widgetDestroy.ts
- assets/cases/ui/04.widget/widgetDestroy.ts.meta
RE： https://github.com/cocos-creator/3d-tasks/issues/1830
> widget destroy case add

- assets/cases/ui/16.coordinate/coordinate-ui-3d.scene
- assets/cases/ui/16.coordinate/coordinate-ui-3d.scene.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/1815
> coordinate-ui-3d add tips

- assets/cases/ui/other/ModelTest.ts
- assets/cases/ui/other/visibility-changed.meta
- assets/cases/ui/other/visibility-changed/visibility-changed.scene
- assets/cases/ui/other/visibility-changed/visibility-changed.scene.meta
- assets/cases/ui/other/visibility-changed/visibility-changed.ts
- assets/cases/ui/other/visibility-changed/visibility-changed.ts.meta
https://github.com/cocos-creator/engine/pull/5762
> visibility changed test case

- assets/cases/base/deprecated.scene
deprecated tips update
RE：https://github.com/cocos-creator/3d-tasks/issues/1976
> deprecated tips update

- assets/cases/animation/low_poly_fox_by_pixelmannen_animated/Materials_scene.meta
- assets/cases/build/altas.meta
- assets/cases/ui/other/uimodel/Capsule.prefab
- assets/cases/ui/other/uimodel/Capsule.prefab.meta
- assets/cases/ui/other/uimodel/uimodel.scene
- assets/cases/ui/other/uimodel/unlit.mtl
- assets/cases/ui/other/uimodel/unlit.mtl.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/1967
> new prefab

- assets/cases/ui/19.static-ui/static-ui.scene
- assets/cases/ui/19.static-ui/static-ui.ts
https://github.com/cocos-creator/engine/pull/5855
> update test case for ui static

- assets/cases/ui/01.sprite/fill-sprite.scene
- assets/cases/ui/01.sprite/simple.scene
- assets/cases/ui/01.sprite/tile.scene
- assets/cases/ui/11.progress/progress.scene
RE:https://github.com/cocos-creator/3d-tasks/issues/1993
> canvas clean flag fixed

- assets/cases/ui/02.label/bmfont-label.scene
Re: https://github.com/cocos-creator/3d-tasks/issues/1996
> 修改了测试例中Transition的类型

- assets/cases/ui/17.sprite-atlas/TS/Test.ts
- assets/cases/ui/17.sprite-atlas/spriteatlas.scene
Re: https://github.com/cocos-creator/3d-tasks/issues/2021
> 修改tips和按钮功能

- assets/cases/ui/18.canvas/multi-canvas.scene
https://github.com/cocos-creator/engine/pull/5881
> add priority in multi-canvas and removed unless test case

- assets/cases/event/MultiTouch.meta
- assets/cases/event/MultiTouch/MultiTouch.scene
- assets/cases/event/MultiTouch/MultiTouch.scene.meta
- assets/cases/event/MultiTouch/MultiTouchCtrl.ts
- assets/cases/event/MultiTouch/MultiTouchCtrl.ts.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/1948
> MultiTouch case

- assets/cases/ui/08.mask/mask-inverted-event.scene
- assets/cases/ui/08.mask/mask-inverted-event.scene.meta
- assets/cases/ui/08.mask/mask-inverted-event.ts
- assets/cases/ui/08.mask/mask-inverted-event.ts.meta
- assets/cases/ui/08.mask/mask.scene
- assets/cases/ui/08.mask/mast-inverted.scene
- assets/cases/ui/08.mask/mast-inverted.scene.meta
https://github.com/cocos-creator/engine/pull/5961
> add mask inverted test case

- assets/cases/ui/08.mask/graphics-mask.scene
- assets/cases/ui/08.mask/graphics-mask.scene.meta
- assets/cases/ui/08.mask/graphics-mask.ts
- assets/cases/ui/08.mask/graphics-mask.ts.meta
https://github.com/cocos-creator/engine/pull/5913
> add graphics mode in mask

- assets/cases/ui/other/opacity.meta
- assets/cases/ui/other/opacity/opacity.scene
- assets/cases/ui/other/opacity/opacity.scene.meta
https://github.com/cocos-creator/engine/pull/5948
> add opacity test case

- assets/cases/ui/15.pageview/pageView_free_verticle.scene
- assets/cases/ui/15.pageview/pageView_free_verticle.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/2043
> optimize the page

- assets/cases/scripting/language-feature/async-functions.meta
- assets/cases/scripting/language-feature/async-functions/AsyncFunctionsTest.scene
- assets/cases/scripting/language-feature/async-functions/AsyncFunctionsTest.scene.meta
- assets/cases/scripting/language-feature/async-functions/AsyncFunctionsTest.ts
- assets/cases/scripting/language-feature/async-functions/AsyncFunctionsTest.ts.meta
This PR adds test-case for testing async function feature of scripting.
To test this feature you should enable the 'AsyncFunctions' polyfills in build configuration.
> Testcase for async functions

- assets/cases/rendering/CullingTestInfo.ts
https://github.com/cocos-creator/3d-tasks/issues/2202
> fix culling scene

- assets/cases/rendertexture/use-render-texture-asset.rt
- assets/cases/rendertexture/use-render-texture-asset.rt.meta
- assets/cases/rendertexture/use-render-texture-asset.scene
- assets/cases/rendertexture/use-render-texture-asset.scene.meta
- assets/cases/rendertexture/use-render-texture-asset.ts.meta
https://github.com/cocos-creator/editor-3d/pull/2908
> update rendertexture asset

- assets/cases/ui/16.coordinate/coordinate-ui-3d.scene
- assets/cases/ui/16.coordinate/coordinate-ui-3d.scene.meta
- assets/cases/ui/16.coordinate/coordinate-ui-3d.ts
- assets/cases/ui/16.coordinate/coordinate-ui-3d.ts.meta
https://github.com/cocos-creator/3d-tasks/issues/2209
https://github.com/cocos-creator/3d-tasks/issues/2178
> tweaks of ui-16-coordinate

- assets/cases/ui/08.mask/mask-inverted.scene
- assets/cases/ui/08.mask/mask-inverted.scene.meta
RE:https://github.com/cocos-creator/3d-tasks/issues/2176
> mask-inverted canvas clean flag fix

- assets/cases/event/MultiTouch/MultiTouch.scene
- assets/cases/event/MultiTouch/MultiTouch.scene.meta
- assets/cases/event/MultiTouch/MultiTouchCtrl.ts
- assets/cases/event/MultiTouch/MultiTouchCtrl.ts.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/2158
> multiTouch update

- assets/cases/ui/08.mask/graphics-mask.scene
- assets/cases/ui/08.mask/graphics-mask.scene.meta
- assets/cases/ui/15.pageview/page-view-ctrl.ts.meta
- assets/cases/ui/15.pageview/page.prefab.meta
- assets/cases/ui/15.pageview/pageView_free_horizontal.scene
- assets/cases/ui/15.pageview/pageView_free_horizontal.scene.meta
- assets/cases/ui/15.pageview/pageView_free_verticle.scene
- assets/cases/ui/15.pageview/pageView_free_verticle.scene.meta
- assets/cases/ui/15.pageview/pageView_unified_horizontal.scene
- assets/cases/ui/15.pageview/pageView_unified_horizontal.scene.meta
- assets/cases/ui/15.pageview/pageView_unified_verticle.scene
- assets/cases/ui/15.pageview/pageView_unified_verticle.scene.meta
- assets/shared-res/textures/ui/sliced/button_green.png.meta
https://github.com/cocos-creator/3d-tasks/issues/2043
https://github.com/cocos-creator/3d-tasks/issues/2161
> fix pageview

- assets/cases/TestList/ListItem.prefab.meta
- assets/cases/TestList/TestList.scene
- assets/cases/TestList/TestList.scene.meta
- assets/cases/TestList/backbutton.ts
- assets/cases/TestList/backbutton.ts.meta
- assets/cases/TestList/exitLeft.png.meta
- assets/cases/TestList/left.png.meta
- assets/cases/TestList/listitem.ts.meta
- assets/cases/TestList/panelBG.png.meta
- assets/cases/TestList/right.png.meta
- assets/cases/TestList/scenelist.ts
- assets/cases/TestList/scenelist.ts.meta
https://github.com/cocos-creator/3d-tasks/issues/2182
> TestList sort

- assets/cases/scripting/language-feature.meta
- assets/cases/scripting/language-feature/async-functions/AsyncFunctionsTest.scene
- assets/cases/scripting/language-feature/async-functions/AsyncFunctionsTest.ts
- assets/cases/ui/ui-log.ts
- assets/cases/ui/ui-log.ts.meta
- assets/resources/log_res.meta
- assets/resources/log_res/item.prefab
- assets/resources/log_res/item.prefab.meta
- assets/resources/log_res/scroll-view-template.prefab
- assets/resources/log_res/scroll-view-template.prefab.meta
https://github.com/cocos-creator/3d-tasks/issues/2163
> add a common output component

- assets/cases/test-build/loadSubPackages.ts
- assets/cases/test-build/test-sub-packages.scene
> update load subpackage test case

- assets/cases/TestList/TestList.scene
- assets/cases/TestList/backbutton.ts
- assets/cases/base/pauseButton.ts
Re: https://github.com/cocos-creator/3d-tasks/issues/2297
> Add Pause judgment

- assets/cases/TestList/TestList.scene
- assets/cases/TestList/backbutton.ts
Re: https://github.com/cocos-creator/3d-tasks/issues/2298
> AddSceneName

- assets/cases/TestList/TestList.scene
- assets/cases/test-build/loadSubPackages.ts
> update subpackage test case && hide testlist scrollbar

- assets/cases/ui/06.scrollview/scroll-view-events.scene
- assets/cases/ui/06.scrollview/scroll-view-events.scene.meta
- assets/cases/ui/06.scrollview/scroll-view-events.ts
- assets/cases/ui/06.scrollview/scroll-view-events.ts.meta
- assets/cases/ui/06.scrollview/scroll-view-rotation.scene
- assets/cases/ui/06.scrollview/scroll-view-rotation.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/2366
https://github.com/cocos-creator/engine/pull/6150
> add scrollview events

- assets/cases/animation/Animations/cube_mainColor.anim
- assets/cases/animation/Animations/cube_mainColor.anim.meta
- assets/cases/animation/Animations/sprite_color.anim
- assets/cases/animation/Animations/sprite_color.anim.meta
- assets/cases/animation/PartAnimation.scene
- assets/cases/animation/PartAnimation.scene.meta
> add part animation test case

- assets/cases/event/event-in-editor/event-in-editor.ts
https://github.com/cocos-creator/3d-tasks/issues/2431
> fixed undo bug after adding script

- assets/cases/test-build/test-js-list.meta
- assets/cases/test-build/test-js-list/plugin.js
- assets/cases/test-build/test-js-list/plugin.js.meta
- assets/cases/test-build/test-js-list/test-js-list.scene
- assets/cases/test-build/test-js-list/test-js-list.scene.meta
- assets/cases/test-build/test-js-list/testJsList.ts
- assets/cases/test-build/test-js-list/testJsList.ts.meta
> add jslist test case

- assets/cases/sub-packages/loadSubPack.ts
- assets/cases/test-build/loadSubPackages.ts
- assets/cases/ui/04.widget/widget-destroy.scene
- assets/cases/ui/other/priority/priority.scene
RE : https://github.com/cocos-creator/3d-tasks/issues/2371
RE : https://github.com/cocos-creator/3d-tasks/issues/2382
> subpack change & tips fix

- assets/cases/ui/08.mask/mask.scene
- assets/cases/ui/15.pageview/page-view-ctrl.ts
- assets/cases/ui/15.pageview/pageView_unified_horizontal.scene
- assets/cases/ui/15.pageview/pageView_unified_verticle.scene
https://github.com/cocos-creator/3d-tasks/issues/2527
> updated ui test case

- assets/cases/particle/particle-velocity.scene
- assets/cases/particle/projectile01_anim.png.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/2538, https://github.com/cocos-creator/3d-tasks/issues/2425
修复 particle-velocity 和 particle-texture-animation 场景问题。
> Fixed 3D particle scene.

- assets/cases/base/pauseButton.ts
RE: https://github.com/cocos-creator/3d-tasks/issues/2547
> game pause case bug fixed

- assets/cases/event/system-event/system-event-PC.scene
- assets/cases/event/system-event/system-event-PC.scene.meta
- assets/cases/event/system-event/system-event-PC.ts
- assets/cases/event/system-event/system-event-PC.ts.meta
Re： https://github.com/cocos-creator/3d-tasks/issues/2523
> systemEvent For PC case add

- assets/cases/ui/15.pageview/page-view-ctrl.ts
Re：https://github.com/cocos-creator/3d-tasks/issues/2627
> fix add page max bug

- assets/cases/ui/19.static-ui/static-ui-replace.scene
- assets/cases/ui/19.static-ui/static-ui-replace.scene.meta
- assets/cases/ui/19.static-ui/static-ui.ts
https://github.com/cocos-creator/3d-tasks/issues/2606
> redesign static UI test cases

- assets/cases/event/event-first.meta
- assets/cases/event/event-first/event-first.scene
- assets/cases/event/event-first/event-first.scene.meta
- assets/cases/event/event-first/event-first.ts
- assets/cases/event/event-first/event-first.ts.meta
- assets/cases/event/event-first/eventNode.prefab
- assets/cases/event/event-first/eventNode.prefab.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/2904
RE: https://github.com/cocos-creator/engine/pull/6473
> event on before join node tree

- assets/cases/ui/other/camera-layout/camera-layout.scene
- assets/cases/ui/other/camera-layout/camera-layout.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/2811
> add test case for camera layout 

- assets/cases/ui/07.richtext/rich-text-align.scene
- assets/cases/ui/07.richtext/rich-text-align.scene.meta
- assets/cases/ui/07.richtext/rich-text.scene
Re： https://github.com/cocos-creator/3d-tasks/issues/2741
> rich text case update

- assets/cases/dynamic-batch/instanced-color.scene
- assets/cases/rendering/static-batcher.ts
Re: 
https://github.com/cocos-creator/3d-tasks/issues/3013
https://github.com/cocos-creator/3d-tasks/issues/3026
rely on https://github.com/cocos-creator/engine/pull/6542
> fix static batching

- assets/cases/event/acceleration.meta
- assets/cases/event/acceleration/acceleration-event.scene
- assets/cases/event/acceleration/acceleration-event.scene.meta
- assets/cases/event/acceleration/acceleration-event.ts
- assets/cases/event/acceleration/acceleration-event.ts.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/3007
> Acceleration case add

- assets/cases/network/NetworkCtrl.ts
- assets/cases/network/network.scene
- assets/cases/network/network.scene.meta
fix label properties
1. fix label size https://github.com/cocos-creator/3d-tasks/issues/2989
2. label cache mode to NONE https://github.com/cocos-creator/3d-tasks/issues/2989
3. rename destroy to  onDestroy https://github.com/cocos-creator/3d-tasks/issues/3032
> fix network test case

- assets/cases/dynamic-batch/instanced-color.scene
https://github.com/cocos-creator/3d-tasks/issues/3026
> fix extension detection

- assets/cases/particle/particle-trail.scene
- assets/cases/particle/particle-trail.scene.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/3131
> Modify particle-trail scene.

- assets/cases/TestList/TestList.scene
- assets/cases/TestList/TestList.scene.meta
- assets/cases/TestList/backbutton.ts
- assets/cases/TestList/backbutton.ts.meta
- assets/cases/TestList/listitem.ts
- assets/cases/TestList/listitem.ts.meta
- assets/cases/ui/04.widget/widget-destroy.scene
- assets/cases/ui/04.widget/widget-destroy.scene.meta
- assets/cases/ui/04.widget/widget-destroy.ts
- assets/cases/ui/04.widget/widget-destroy.ts.meta
Re：https://github.com/cocos-creator/3d-tasks/issues/2338
Re：https://github.com/cocos-creator/3d-tasks/issues/2339
> format fix

- assets/cases/network/network.scene
- assets/cases/network/network.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/2989 
bugfix: 清屏
> fix network test case, add clear flag

- assets/cases/scripting/asset_loading/AssetLoading.scene
- assets/cases/scripting/asset_loading/AssetLoading.scene.meta
- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts
- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts.meta
RE：https://github.com/cocos-creator/3d-tasks/issues/3157
> assetloading bug fix

- assets/cases/scripting/asset_loading/LoadRes/LoadRes_example.ts
- assets/cases/scripting/asset_loading/LoadRes/LoadRes_example.ts.meta
- assets/cases/scripting/asset_loading/LoadResDir/LoadResDir_example.ts
- assets/cases/scripting/asset_loading/LoadResDir/LoadResDir_example.ts.meta
- assets/resources/test_assets/testMat.mtl
RE: https://github.com/cocos-creator/3d-tasks/issues/3037
> builtIn asset release protect

- assets/cases/network/NetworkCtrl.ts
RE: https://github.com/cocos-creator/3d-tasks/issues/3196
> webSocket update

- assets/cases/light/lighting.scene
- assets/cases/light/lighting.scene.meta
- assets/cases/light/sphere_light.ts
- assets/cases/light/sphere_light.ts.meta
- assets/cases/light/sport_light_1.ts
- assets/cases/light/sport_light_1.ts.meta
- assets/cases/light/sport_light_2.ts
- assets/cases/light/sport_light_2.ts.meta
https://github.com/troublemaker52025/3d-tasks/blob/master/design-docs/render-pipeline/forward-pipeline-lighting.md
https://github.com/cocos-creator/engine/pull/6596
https://github.com/cocos-creator/engine/pull/6630
> light test

- assets/cases/animation/Animations/Easing_Bounce.anim
- assets/cases/animation/Animations/Easing_Bounce.anim.meta
- assets/cases/animation/Animations/Easing_Linear.anim
- assets/cases/animation/Animations/Easing_Linear.anim.meta
- assets/cases/animation/Animations/Easing_Sine.anim
- assets/cases/animation/Animations/Easing_Sine.anim.meta
- assets/cases/animation/EasingMethods.scene
- assets/cases/animation/EasingMethods.scene.meta
> 增加插值动画的测试例

- assets/cases/ui/01.sprite/trimmed.scene
- assets/cases/ui/01.sprite/trimmed.ts
- assets/cases/ui/12.editbox/editbox-ctrl.scene
re: https://github.com/cocos-creator/3d-tasks/issues/2689
> tips remove & trimmed scene fix

- assets/cases/TestList/TestList.scene
- assets/cases/TestList/backbutton.ts
RE： https://github.com/cocos-creator/3d-tasks/issues/2693
> testlist update

- assets/cases/single-compress/draw.ts
- assets/cases/single-compress/draw.ts.meta
- assets/cases/single-compress/image/etc1_rgb.png.meta
- assets/cases/single-compress/image/jpg.png.meta
- assets/cases/single-compress/image/pvrtc2_rgb.png.meta
- assets/cases/single-compress/image/pvrtc2_rgba.png.meta
- assets/cases/single-compress/image/pvrtc4_rgb.png.meta
- assets/cases/single-compress/image/pvrtc4_rgba.png.meta
- assets/cases/single-compress/image/webp.png.meta
- assets/cases/single-compress/single-compress.scene
- assets/cases/single-compress/single-compress.scene.meta
Resolves: cocos-creator/3d-tasks#3452
> add tips in single-compress case

- assets/cases/TestList/TestList.scene
RE: https://github.com/cocos-creator/3d-tasks/issues/2693
> testlist bug fix

- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts
RE：https://github.com/cocos-creator/3d-tasks/issues/3459
RE：https://github.com/cocos-creator/3d-tasks/issues/3453
RE：https://github.com/cocos-creator/3d-tasks/issues/3446
> assetload bug fix

- assets/cases/animation/EasingMethods.scene
- assets/cases/compressed-texture/compressed-texture.scene
- assets/cases/compressed-texture/sheep_down_0.png.meta
- assets/cases/compressed-texture/sheep_down_1.png.meta
- assets/cases/compressed-texture/sheep_down_2.png.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/3448
RE: https://github.com/cocos-creator/3d-tasks/issues/3442
> compress texture change & tips

- assets/cases/bytecode.meta
- assets/cases/bytecode/ByteCodeCache.ts
- assets/cases/bytecode/ByteCodeCache.ts.meta
- assets/cases/bytecode/ByteCodeLoader.ts
- assets/cases/bytecode/ByteCodeLoader.ts.meta
- assets/cases/bytecode/bytecode.scene
- assets/cases/bytecode/bytecode.scene.meta
ref https://github.com/cocos-creator/cocos2d-x-lite/pull/2434
字节码测试用例
> 3dgfx add bytecode

- assets/cases/TestList/backbutton.ts
Re: https://github.com/cocos-creator/3d-tasks/issues/3309
Re: https://github.com/cocos-creator/3d-tasks/issues/3592
> static-ui-replace remove from list

- assets/cases/ui/04.widget/advance-widget.scene
- assets/cases/ui/06.scrollview/list-view.scene
RE: https://github.com/cocos-creator/3d-tasks/issues/3579
> label width fix

- assets/cases/bytecode/ByteCodeCache.ts
- assets/cases/bytecode/ByteCodeLoader.ts
> Bytecode testcase update with tslint

- assets/cases/ui/12.editbox/editbox.scene
Re: https://github.com/cocos-creator/3d-tasks/issues/3677
> editbox height change

- assets/cases/rendertexture/capture_to_web.ts
- assets/cases/rendertexture/render-camera-to-model.ts
- assets/cases/rendertexture/render-ui-to-model.ts
- assets/cases/rendertexture/render-ui-to-spriteframe.ts
> fix render texture color and depthStencil format (#254)

- assets/cases/event/multiTouch/MultiTouchCtrl.ts
- assets/cases/event/multiTouch/multiTouch.scene
RE: https://github.com/cocos-creator/3d-tasks/issues/2158
> multiTouch case update

- assets/cases/base/gamePause.scene
- assets/cases/base/pauseButton.ts
RE: https://github.com/cocos-creator/3d-tasks/issues/3991
RE: https://github.com/cocos-creator/3d-tasks/issues/3992
> gamePause case update

- assets/cases/ui/09.toggle/toggle-ctrl.ts
- assets/cases/ui/09.toggle/toggle-ctrl.ts.meta
- assets/cases/ui/09.toggle/toggle-event-ctrl.ts
- assets/cases/ui/09.toggle/toggle-event-ctrl.ts.meta
- assets/cases/ui/09.toggle/toggle-event.scene
- assets/cases/ui/09.toggle/toggle-event.scene.meta
- assets/cases/ui/09.toggle/toggle.scene
https://github.com/cocos-creator/3d-tasks/issues/3960
关联 pr: https://github.com/cocos-creator/engine/pull/7057
效果图：
> update toggle cases

- assets/cases/ui/14.graphics/graphics-line-join.scene
- assets/cases/ui/14.graphics/graphics-line-join.scene.meta
- assets/cases/ui/14.graphics/graphics-line-join.ts
- assets/cases/ui/14.graphics/graphics-line-join.ts.meta
re: https://github.com/cocos-creator/engine/pull/7164
> add graphics line join test

- assets/cases/event/multiTouch/MultiTouchCtrl.ts
Re: https://github.com/cocos-creator/engine/pull/7162
> sync multi-touch adjustment （engine pr #7162）

- assets/cases/ui/06.scrollview/list-view-ctrl.ts
> improve list view case

- assets/cases/ui/15.pageview/pageView_free_horizontal.scene
- assets/cases/ui/15.pageview/pageView_free_verticle.scene
- assets/cases/ui/15.pageview/pageView_unified_horizontal.scene
- assets/cases/ui/15.pageview/pageView_unified_verticle.scene
Re: https://github.com/cocos-creator/3d-tasks/issues/4200
> adjust ui test-cases-3d for 1.2 issue

- assets/cases/ui/06.scrollview/list-view-ctrl.ts
- assets/cases/ui/06.scrollview/list-view-ctrl.ts.meta
- assets/cases/ui/06.scrollview/list-view.scene
- assets/cases/ui/06.scrollview/list-view.scene.meta
- assets/cases/ui/06.scrollview/scroll-view-events.scene
- assets/cases/ui/06.scrollview/scroll-view-events.scene.meta
- assets/cases/ui/06.scrollview/scroll-view-events.ts.meta
- assets/cases/ui/06.scrollview/scroll-view-rotation.scene
- assets/cases/ui/06.scrollview/scroll-view-rotation.scene.meta
- assets/cases/ui/06.scrollview/scroll-view.scene
- assets/cases/ui/06.scrollview/scroll-view.scene.meta
- assets/cases/ui/15.pageview/page-view-ctrl.ts.meta
- assets/cases/ui/15.pageview/page.prefab
- assets/cases/ui/15.pageview/page.prefab.meta
- assets/cases/ui/15.pageview/pageView_free_horizontal.scene
- assets/cases/ui/15.pageview/pageView_free_horizontal.scene.meta
- assets/cases/ui/15.pageview/pageView_free_verticle.scene
- assets/cases/ui/15.pageview/pageView_free_verticle.scene.meta
- assets/cases/ui/15.pageview/pageView_unified_horizontal.scene
- assets/cases/ui/15.pageview/pageView_unified_horizontal.scene.meta
- assets/cases/ui/15.pageview/pageView_unified_verticle.scene
- assets/cases/ui/15.pageview/pageView_unified_verticle.scene.meta
回退之前对 scrollview and page view content 的修改
engine pr 关联：https://github.com/cocos-creator/engine/pull/7229
> Revert scrollview and page view content change

- assets/cases/ui/07.richtext/rich-text-align.scene
- assets/cases/ui/07.richtext/rich-text-align.scene.meta
- assets/cases/ui/07.richtext/rich-text-event.scene
- assets/cases/ui/07.richtext/rich-text-event.scene.meta
- assets/cases/ui/07.richtext/rich-text-event.ts
- assets/cases/ui/07.richtext/rich-text-event.ts.meta
- assets/cases/ui/07.richtext/rich-text-wrap.scene
- assets/cases/ui/07.richtext/rich-text-wrap.scene.meta
- assets/cases/ui/07.richtext/rich-text.scene
- assets/cases/ui/07.richtext/rich-text.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/4254
调整 rich text 事件弹出的 tips 信息位置
> improve rich text case for 3d-tasks/issues/4254

- assets/cases/atlas-compress/atlas-compress.scene
- assets/cases/atlas-compress/atlas-compress.scene.meta
Re：https://github.com/cocos-creator/3d-tasks/issues/4241
> atlas compress case update

- settings/1.2.0/packages/builder.json
- settings/1.2.0/packages/project.json
https://github.com/cocos-creator/3d-tasks/issues/4223
> update project settings

- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts
- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts.meta
Re：https://github.com/cocos-creator/3d-tasks/issues/4205
> load material bug fix

- assets/cases/event/multiTouch/multiTouch.scene
Re: https://github.com/cocos-creator/3d-tasks/issues/4219
> fixed event parameter loss

- assets/cases/rendertexture/targetTexture.meta
- assets/cases/rendertexture/targetTexture/camera-render-texture.rt
- assets/cases/rendertexture/targetTexture/camera-render-texture.rt.meta
- assets/cases/rendertexture/targetTexture/cameraUseRenderTex.scene
- assets/cases/rendertexture/targetTexture/cameraUseRenderTex.scene.meta
- assets/cases/rendertexture/targetTexture/canvas-render-texture.rt
- assets/cases/rendertexture/targetTexture/canvas-render-texture.rt.meta
- assets/cases/rendertexture/targetTexture/canvasUseRenderTex.scene
- assets/cases/rendertexture/targetTexture/canvasUseRenderTex.scene.meta
- assets/cases/rendertexture/targetTexture/quadForRenderTex.effect
- assets/cases/rendertexture/targetTexture/quadForRenderTex.effect.meta
- assets/cases/rendertexture/targetTexture/quadForRenderTex.mtl
- assets/cases/rendertexture/targetTexture/quadForRenderTex.mtl.meta
- assets/cases/rendertexture/targetTexture/use-render-texture-to-model.ts
- assets/cases/rendertexture/targetTexture/use-render-texture-to-model.ts.meta
- assets/cases/rendertexture/targetTexture/use-render-texture-to-sprite.ts
- assets/cases/rendertexture/targetTexture/use-render-texture-to-sprite.ts.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/4473
> RenderTexture With TargetTexture case add

- assets/cases/ui/07.richtext/rich-text.scene
- assets/cases/ui/07.richtext/rich-text.scene.meta
Re： https://github.com/cocos-creator/3d-tasks/issues/4269
> richText case bug fix

- assets/cases/ui/04.widget/align-mode.scene
- assets/cases/ui/04.widget/align-mode.scene.meta
Re：https://github.com/cocos-creator/engine/pull/7467
> add widget resize mode case

- assets/cases/ui/21.video-player/video-player-ctrl.ts
- assets/cases/ui/22.webview.meta
- assets/cases/ui/22.webview/webview-ctrl.ts
- assets/cases/ui/22.webview/webview-ctrl.ts.meta
- assets/cases/ui/22.webview/webview.scene
- assets/cases/ui/22.webview/webview.scene.meta
cocos-creator/3d-tasks/issues/3759
> add web view case

- assets/cases/ui/23.safe-area.meta
- assets/cases/ui/23.safe-area/safe-area.scene
- assets/cases/ui/23.safe-area/safe-area.scene.meta
> add safe area case

- assets/cases/ui/21.video-player/video-player-ctrl.ts
- assets/cases/ui/21.video-player/video-player-ctrl.ts.meta
- assets/cases/ui/21.video-player/video-player.scene
- assets/cases/ui/21.video-player/video-player.scene.meta
- assets/cases/ui/22.webview/webview-ctrl.ts
- assets/cases/ui/22.webview/webview-ctrl.ts.meta
- assets/cases/ui/22.webview/webview.scene
- assets/cases/ui/22.webview/webview.scene.meta
- settings/3.0.0/packages/engine.json
完善 video player 与 web view 添加平台不支持提示
open ENABLE_TRANSPARENT_CANVAS
目前只有 web 平台支持，其他的都还没适配完全，适配完全后在开启
> improve video player and web view

- assets/cases/ui/21.video-player.meta
- assets/cases/ui/21.video-player/video-player-ctrl.ts
- assets/cases/ui/21.video-player/video-player.scene
- assets/cases/ui/22.webview.meta
- assets/cases/ui/22.webview/webview-ctrl.ts
- assets/cases/ui/22.webview/webview.scene
微信小游戏开启 video player，并且完善一下 video player 与 web view 的范例
> open video player cases for wechat game

- assets/cases/ui/21.video-player/video-player-ctrl.ts
- assets/cases/ui/21.video-player/video-player.scene
调整了一下 video player 的范例
不默认加 video clip，点击在进行加载
> improve video player cases

- assets/cases/tiled-map/shield-node.ts
resolve https://github.com/cocos-creator/3d-tasks/issues/4804
replace `Vec2::sub()` method
> [v3.0] fix tiledmap testcase

- assets/cases/base/gamePause.scene
- assets/cases/base/gamePause.scene.meta
- assets/cases/ui/04.widget/widget-destroy.scene
- assets/cases/ui/04.widget/widget-destroy.scene.meta
- assets/cases/ui/04.widget/widget-destroy.ts
- assets/cases/ui/04.widget/widget-destroy.ts.meta
- assets/cases/ui/04.widget/widget-performance.scene
- assets/cases/ui/04.widget/widget-performance.scene.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/4811
> widget destroy case update& game pause tips update & widget performance tips change

- assets/cases/camera/camera.scene
- assets/cases/camera/camera.scene.meta
- assets/cases/scripting/build-time-constants-test/BuildTimeConstantsTest.ts
https://github.com/cocos-creator/3d-tasks/issues/4793
https://github.com/cocos-creator/3d-tasks/issues/5021
> update multiple viewport scene

- assets/cases/raycast/wire-frame.ts
- assets/cases/raycast/wire-frame.ts.meta
> raycast-mesh bug fix

- assets/cases/ui/21.video-player/video-player-ctrl.ts
- assets/cases/ui/22.webview/webview-ctrl.ts
打开安卓平台与 IOS 平台的 video player 与 web view 测试用例
关联 issue ：https://github.com/cocos-creator/3d-tasks/issues/4967
> open video player and web view cases  for android and iOS platform

- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts
- assets/cases/scripting/asset_loading/LoadRes.scene
- assets/cases/scripting/asset_loading/PreloadAssets.scene
- assets/cases/scripting/asset_loading/PreloadAssets/PreloadAssets.ts
- assets/resources/test_assets/back-to-asset-loading.ts
- assets/resources/test_assets/back-to-asset-loading.ts.meta
- assets/resources/test_assets/test-preload-scene.scene
- assets/resources/test_assets/test-preload-scene.scene.meta
- assets/resources/test_assets/test-scene.scene
- assets/resources/test_assets/test-scene.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/5146
https://github.com/cocos-creator/3d-tasks/issues/5167
https://github.com/cocos-creator/3d-tasks/issues/5125
> Use different scene to load

- assets/cases/network/NetworkCtrl.ts
https://github.com/cocos-creator/3d-tasks/issues/5031
> fix cacert path is not correct

- assets/cases/scripting/build-time-constants-test/BuildTimeConstantsTest.ts
- assets/cases/scripting/build-time-constants-test/BuildTimeConstantsTest.ts.meta
- assets/cases/ui/07.richtext/rich-text.scene
- assets/cases/ui/07.richtext/rich-text.scene.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/5196
> fix buildTimeConstants bug & richtext font family change

- assets/cases/base/pause.ts
- assets/cases/base/pause.ts.meta
Re： https://github.com/cocos-creator/3d-tasks/issues/5202
> gamepause protect

- assets/cases/animation/scripts/MorphController.ts
re: https://github.com/cocos-creator/3d-tasks/issues/5276
> use EDITOR instead of CC_EDITOR

- assets/cases/spine/LoadSpine.scene
- assets/cases/spine/SpineAttach.scene
- assets/cases/spine/SpineBoy.scene
- assets/cases/spine/SpineCollider.scene
- assets/cases/spine/SpineMesh.scene
- assets/cases/spine/SpineSkin.scene
- assets/cases/sub-packages/sub-pack-01/subPack01.scene
- assets/cases/sub-packages/sub-pack-01/subPack01.scene.meta
- assets/cases/sub-packages/sub-pack-02/subPack02.scene
- assets/cases/sub-packages/sub-pack-02/subPack02.scene.meta
- assets/cases/sub-packages/sub-packages.scene
- assets/cases/sub-packages/sub-packages.scene.meta
- assets/cases/tiled-map/Hexa.scene
- assets/cases/tiled-map/dynamic-tiled-map.scene
- assets/cases/tiled-map/object-group-image.scene
- assets/cases/tiled-map/puzzle.scene
- assets/cases/tiled-map/shield-node.scene
- assets/cases/ui/08.mask/mask-inverted.scene
- assets/cases/ui/08.mask/mask-inverted.scene.meta
- assets/cases/ui/21.video-player/video-player.scene
RE： https://github.com/cocos-creator/3d-tasks/issues/5122
> canvas clean color fix

- assets/cases/ui/23.safe-area/safe-area.scene
- assets/cases/ui/23.safe-area/safe-area.scene.meta
调整一下 safe area 中心的金币的 widget，让居中表示
> improve safe area

- assets/cases/shadow-map/cocos/body-instanced.mtl
- assets/cases/shadow-map/cocos/body.mtl
- assets/cases/shadow-map/cocos/helmet-instanced.mtl
- assets/cases/shadow-map/cocos/helmet.mtl
> fix shadowmap material

- assets/cases/ui/08.mask/mask-use-image-stencil.ts
- assets/cases/ui/08.mask/mask-use-image-stencil.ts.meta
RE： https://github.com/cocos-creator/3d-tasks/issues/5328
> mask use image stencil script update

- assets/cases/animation/scripts/MorphController.ts
- assets/cases/scripting/build-time-constants-test/BuildTimeConstantsTest.ts
https://github.com/cocos-creator/editor-3d/pull/4790
> Rename `cce:env` to `cc/env`

- assets/cases/ui/08.mask/mask-use-image-stencil.scene
- assets/cases/ui/08.mask/mask-use-image-stencil.ts
Re: https://github.com/cocos-creator/engine/pull/7936
> simultaneously modify test cases according to mask pr

- assets/cases/network/NetworkCtrl.ts
> fix pem url

- assets/cases/ui/14.graphics/graphics-draw-before-init.scene
- assets/cases/ui/14.graphics/graphics-draw-before-init.scene.meta
- assets/cases/ui/14.graphics/graphics-draw-before-init.ts
- assets/cases/ui/14.graphics/graphics-draw-before-init.ts.meta
depend on: https://github.com/cocos-creator/engine/pull/7949
> provide graphics prior to component initialization data filling test cases(#7949)

- assets/cases/ui/05.layout/layout-basic-grid.scene
- assets/cases/ui/05.layout/layout-basic-grid.scene.meta
- assets/cases/ui/05.layout/layout-basic-horizontal.scene
- assets/cases/ui/05.layout/layout-basic-horizontal.scene.meta
- assets/cases/ui/05.layout/layout-basic-verticle.scene
- assets/cases/ui/05.layout/layout-basic-verticle.scene.meta
- assets/cases/ui/05.layout/layout-change-order.ts
- assets/cases/ui/05.layout/layout-change-order.ts.meta
- assets/cases/ui/05.layout/layout-change-sibling.scene
- assets/cases/ui/05.layout/layout-change-sibling.scene.meta
- assets/cases/ui/05.layout/layout-grid-contraint.scene
- assets/cases/ui/05.layout/layout-grid-contraint.scene.meta
- assets/cases/ui/05.layout/layout-scrollview.scene
- assets/cases/ui/05.layout/layout-size-changed.scene
- assets/cases/ui/05.layout/layout-size-changed.scene.meta
Depend on: https://github.com/cocos-creator/engine/pull/7970
> layout more test cases

- assets/cases/scripting/asset_loading/LoadResDir/LoadResDir_example.ts
https://github.com/cocos-creator/3d-tasks/issues/5608
> fix release effect

- assets/cases/asset-bundle/test-bundle.meta
> support subpackage on byteDance

- assets/cases/ui/08.mask/mask-use-image-stencil.scene
- assets/cases/ui/08.mask/mask-use-image-stencil.scene.meta
RE： https://github.com/cocos-creator/3d-tasks/issues/5650
> mask use image stencil bug fix

- assets/cases/animation/scripts/MorphController.ts
> fix send message

- assets/cases/base/gamePause.scene
- assets/cases/base/gamePause.scene.meta
- assets/cases/base/pauseButton.ts
- assets/cases/base/pauseButton.ts.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/5452
> gamePause case change

- assets/cases/scripting/asset_loading/AssetLoading/AssetLoading.ts
https://github.com/cocos-creator/3d-tasks/issues/5760
> small fixes

- assets/cases/network/NetworkCtrl.ts
https://github.com/cocos-creator/3d-tasks/issues/5758
> fix network cacert

- assets/cases/ui/21.video-player/video-player-ctrl.ts
> update event type callback function parameters

- assets/cases/ui/21.video-player/video-player-ctrl.ts
> improve video-player-ctrl code

- assets/cases/particle/particle-main.scene
- assets/cases/particle/particle-renderer.scene
- assets/cases/particle/particle-shape.scene
- assets/cases/ui/25.particle/particle-2d-sprite-change.scene
https://github.com/cocos-creator/3d-tasks/issues/5775
> Fix tips of particle scene.

- assets/cases/ui/08.mask/mask-nesting.scene
- assets/cases/ui/08.mask/mask-nesting.scene.meta
RE：https://github.com/cocos-creator/engine/pull/8140
> add mask nesting case

- assets/cases/2d-rendering-in-3d/2d-rendering-in-3d.scene
delete deprecated script model
> fix missing script in 2d-rendering-in-3d testcase

- assets/cases/ui/21.video-player/video-player-ctrl.ts
resolve  https://github.com/cocos-creator/3d-tasks/issues/6059
相关 pr: https://github.com/cocos-creator/engine/pull/8169
> play video after  ready to play

- assets/cases/scripting/asset_loading/LoadResDir.scene
- assets/cases/scripting/asset_loading/LoadResDir.scene.meta
- assets/cases/ui/12.editbox/editbox-ctrl.ts
- assets/shared-res/prefabs/loaditem.prefab
- assets/shared-res/prefabs/loaditem.prefab.meta
RE: https://github.com/cocos-creator/3d-tasks/issues/5774
RE: https://github.com/cocos-creator/3d-tasks/issues/5764
> loadresDir change & editBox Ctrl bug fix

- assets/cases/ui/08.mask/mask-nesting.scene
RE: https://github.com/cocos-creator/3d-tasks/issues/6141
RE: https://github.com/cocos-creator/3d-tasks/issues/6143
> fix mask-nesting camera clean flag

- assets/cases/ui/21.video-player/video-player-ctrl.ts
https://github.com/cocos-creator/3d-tasks/issues/6148
完善 video player 解决在手机浏览器上无法播放的问题
> Fix the problem of mobile video player not playing

- assets/cases/2d-rendering-in-3d/2d-rendering-in-3d.scene
- assets/cases/2d-rendering-in-3d/2d-rendering-in-3d.scene.meta
原场景无法显示plane等3d节点 （猜测是之前上传时数据丢失）
使用新场景替换了原场景
> Fix 3d object missing bug

- assets/cases/2d-rendering-in-3d/2d-rendering-in-3d.scene
- assets/cases/2d-rendering-in-3d/depth-test-spine.mtl
- assets/cases/2d-rendering-in-3d/depth-test-spine.mtl.meta
- assets/cases/2d-rendering-in-3d/depth-test.mtl
- assets/cases/2d-rendering-in-3d/depth-test.mtl.meta
RE：https://github.com/cocos-creator/engine/pull/8205
> open depth by material

- assets/cases/rendertexture/render-camera-to-model.scene
- assets/cases/rendertexture/render-camera-to-model.scene.meta
- assets/cases/rendertexture/render-ui-to-model.scene
- assets/cases/rendertexture/render-ui-to-model.scene.meta
- assets/cases/rendertexture/render-ui-to-spriteframe.scene
- assets/cases/rendertexture/render-ui-to-spriteframe.scene.meta
- assets/cases/rendertexture/targetTexture/canvasUseRenderTex.scene
- assets/cases/rendertexture/targetTexture/canvasUseRenderTex.scene.meta
RE：https://github.com/cocos-creator/3d-tasks/issues/5977
> change renderTexture camera priority

- assets/cases/dragonbones/DragonBonesCtrl.ts
修复issue: https://github.com/cocos-creator/3d-tasks/issues/6138
> Fix Dragonbones ClickEvent bug

- assets/cases/tiled-map/shield-node.ts
相关issue: https://github.com/cocos-creator/3d-tasks/issues/6256#issuecomment-773875491
> fix EventTouch move bug

- assets/cases/ui/04.widget/widget-destroy.scene
RE：https://github.com/cocos-creator/engine/pull/8304
> change widget destroy case tips

- assets/cases/particle/particle-main.scene
- assets/cases/particle/particle-renderer.scene
- assets/cases/particle/particle-shape.scene
- assets/cases/ui/17.sprite-atlas/spriteatlas.scene
RE: https://github.com/cocos-creator/3d-tasks/issues/6512
> Particle tips bug fix

- assets/cases/ui/05.layout/layout-change-order.ts
- assets/cases/ui/05.layout/layout-change-order.ts.meta
- assets/cases/ui/05.layout/layout-change-sibling.scene
RE: https://github.com/cocos-creator/3d-tasks/issues/6956
> change sibling case

- assets/shared-res/first-person-camera.ts
https://github.com/cocos-creator/3d-tasks/issues/4417
> numerically more robust camera control

- assets/cases/ui/04.widget/widget-destroy.scene
RE： https://github.com/cocos-creator/3d-tasks/issues/7020
> fix spell wrong

- assets/cases/rendering/CullingTestInfo.ts
- assets/cases/rendering/CullingTestInfo.ts.meta
https://github.com/cocos-creator/3d-tasks/issues/6794
> fix culling scene detection list failure

- assets/cases/rendering/CullingTestInfo.ts
> fix cullingScene bug for mac

- assets/cases/spine/SpineAttach.scene
- assets/cases/spine/SpineAttach.ts
- assets/cases/spine/SpineAttach.ts.meta
1. change cache mode info text, i think it is a mistake issue.
> spine cache mode not support change attach slot.

- assets/cases/spine/SpineAttach.scene
- assets/cases/spine/SpineAttach.ts
* spine cache mode not support change attach slot.
* change button status for test.
* remove unused check code.
(cherry picked from commit 3b2f633cbc0d3a93b2c0d8f0379fe4f2a0d706eb)
> spine cache mode not support change attach slot. (#449)

- settings/v2/packages/builder.json
resolve https://github.com/cocos-creator/3d-tasks/issues/7591
> [3.1.x] Remove invalid config of compressed texture

- assets/cases/event/system-event/keyboard-event.scene
- assets/cases/event/system-event/keyboard-event.ts
changeLog:
- 修改按键事件
- 补充已知问题
依赖 pr: https://github.com/cocos-creator/engine/pull/8785
> 优化 Keyboard 测试例

- assets/cases/spine/SpineBoyCtrl.ts
https://github.com/cocos-creator/3d-tasks/issues/7683
> fix spineBoy

- assets/cases/TestList/TestList.scene
- assets/cases/TestList/backbutton.ts
- assets/cases/TestList/get-version.ts
- assets/cases/TestList/get-version.ts.meta
- assets/cases/test-build/test-atlas-config.ts
reply: https://github.com/cocos-creator/3d-tasks/issues/7879
> [3.1.2] Add engine version in testList.scene for test

- assets/cases/audio/audioControl.scene
- assets/cases/base/screenTest.scene
- assets/cases/base/screenTest.scene.meta
- assets/cases/base/screenTest.ts
- assets/cases/base/screenTest.ts.meta
> 增加 fullscreen 测试例

- assets/cases/event/system-event/TimeLabel.prefab
- assets/cases/event/system-event/TimeLabel.prefab.meta
- assets/cases/event/system-event/show-hide-event.scene
- assets/cases/event/system-event/show-hide-event.scene.meta
- assets/cases/event/system-event/show-hide-event.ts
- assets/cases/event/system-event/show-hide-event.ts.meta
> 增加前后台事件测试例

- assets/cases/event/acceleration/acceleration-event.ts
- assets/cases/ui/23.safe-area/safe-area.scene
- assets/cases/ui/23.safe-area/safe-area.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/7537
- 优化加速计测试例
- 更新 safe-area 相关已知问题说明
> 更新 safe-area 相关已知问题说明 && 优化加速计测试例

- assets/cases/ui/other/opacity/auto-change-opacity.ts
- assets/cases/ui/other/opacity/auto-change-opacity.ts.meta
- assets/cases/ui/other/opacity/opacity-auto.scene
- assets/cases/ui/other/opacity/opacity-auto.scene.meta
RE： https://github.com/cocos-creator/3d-tasks/issues/7332
> auto change opacity case add

- assets/cases/scripting/asset_loading/LoadRes.scene
- assets/cases/scripting/asset_loading/LoadRes.scene.meta
- assets/cases/ui/04.widget/advance-widget.scene
- assets/cases/ui/04.widget/advance-widget.scene.meta
RE： https://github.com/cocos-creator/3d-tasks/issues/6786
> update label overflow mode for vivo default font

- assets/cases/ui/17.sprite-atlas/TS/Test.ts
- assets/cases/ui/17.sprite-atlas/spriteatlas.scene
- assets/cases/ui/17.sprite-atlas/spriteatlas.scene.meta
https://github.com/cocos-creator/3d-tasks/issues/7853
> update sprite Atlas case

- assets/cases/ui/other/opacity/auto-change-opacity.ts
- assets/cases/ui/other/opacity/opacity-auto.scene
- assets/cases/ui/other/opacity/opacity-auto.scene.meta
- assets/cases/ui/other/opacity/stringChange.ts
- assets/cases/ui/other/opacity/stringChange.ts.meta
https://github.com/cocos-creator/engine/pull/9057
https://github.com/cocos-creator/engine/pull/9049
> update auto test opacity case

- assets/cases/base/screenTest.scene
https://github.com/cocos-creator/3d-tasks/issues/8218
之前的 camera 设置是 clearDepthBit，应该是 clearColorBit
> update screenTest clearFlags

- assets/cases/dragonbones/DragonBonesCtrl.ts
- assets/cases/tiled-map/puzzle.ts
refer: https://github.com/cocos-creator/3d-tasks/issues/8194
> use new enum instead

- assets/cases/animation/scripts/MorphController.ts
Re: https://github.com/cocos-creator/3d-tasks/issues/8273
changeLog:
- 移除 MorphController console log 逻辑，这块打印一个对象，在一些平台上消耗太大了，容易导致崩溃
> remove console log on morph slider change event

- assets/cases/scripting/asset_loading/LoadResDir/LoadResDir_example.ts
https://github.com/cocos-creator/3d-tasks/issues/6772
> fix mesh was destroyed before used

- assets/cases/base/restart.scene
- assets/cases/base/restart.scene.meta
- assets/cases/base/restart.ts
- assets/cases/base/restart.ts.meta
* 添加各平台restart功能测试，点击按钮重启游戏
1. 重启之后显示效果是否回到主页
2. 原生平台安卓和ios需要测试重启之后切换到后台，再切回来，是否显示正常。
3. Runtime仍是重启场景回到最开始的场景
> add restart test case

- assets/cases/spine/SpineBoyCtrl.ts
* https://github.com/cocos-creator/3d-tasks/issues/8731
> set to setup pose after stop previous animation

- assets/cases/ui/17.sprite-atlas/TS/Test.ts
https://github.com/cocos-creator/3d-tasks/issues/8724
> fix spriteatlas bug

- assets/cases/rendertexture/duck-unlit-tex.mtl
- assets/cases/rendertexture/duck-unlit-tex.mtl.meta
- assets/cases/rendertexture/render-ui-to-spriteframe.scene
- assets/cases/rendertexture/render-ui-to-spriteframe.scene.meta
> Fix the deferred pipeline render-ui-to-spriteframe scene crashes under metal

- assets/shared-res/cocos/helmet.mtl
* https://github.com/cocos-creator/3d-tasks/issues/9030
头盔透明材质使用useInstancing模式渲染顺序会有问题，可以待问题解决再打开
> modify helmet not use instancing mode

- assets/test-plugin.js
- assets/test-plugin.js.meta
https://github.com/cocos-creator/3d-tasks/issues/8019
https://github.com/cocos-creator/3d-tasks/issues/5240
> clean cache when launch test case

- assets/cases/rendertexture/read-pixels/RTCapture.ts
- assets/cases/rendertexture/read-pixels/RTCapture.ts.meta
- assets/cases/rendertexture/read-pixels/RTPixel.ts
- assets/cases/rendertexture/read-pixels/RTPixel.ts.meta
- assets/cases/rendertexture/read-pixels/rt-read-pixels.scene
- assets/cases/rendertexture/read-pixels/rt-read-pixels.scene.meta
- assets/cases/rendertexture/read-pixels/sprite-mat.mtl
- assets/cases/rendertexture/read-pixels/sprite-mat.mtl.meta
* https://github.com/cocos-creator/3d-tasks/issues/8701
> add test case for copytexturetobuffer

- settings/v2/packages/engine.json
RE：https://github.com/cocos-creator/engine/pull/9378
> select GPU Driven On

- assets/cases/rendering/toon-shader.scene
- assets/shared-res/models/an/an.prefab
- assets/shared-res/models/an/an.prefab.meta
> fix partcile prefab bug in toon shader scene

- assets/cases/ui/06.scrollview/scroll-view-bounce-back.scene
- assets/cases/ui/06.scrollview/scroll-view-bounce-back.scene.meta
- assets/cases/ui/06.scrollview/scroll-view-bounce-back.ts
- assets/cases/ui/06.scrollview/scroll-view-bounce-back.ts.meta
- assets/cases/ui/06.scrollview/scroll-view-scroll-to-offset.scene
- assets/cases/ui/06.scrollview/scroll-view-scroll-to-offset.scene.meta
- assets/cases/ui/06.scrollview/scroll-view-scroll-to-offset.ts
- assets/cases/ui/06.scrollview/scroll-view-scroll-to-offset.ts.meta
https://github.com/cocos-creator/3d-tasks/issues/8443
https://github.com/cocos-creator/3d-tasks/issues/8257
* 针对 #8443，创建场景，左右拖动scrollview出边界并使其回弹，观察log打印，非无限打印情况即符合期望
* 针对 #8257，创建场景，左右拖动scrollview可以看到下面的实时offset，可以通过点击随机按钮来调用ScrollToOffset函数来观察参数offset和结果offset的关系
> supplement scrollview test cases #8443 #8257

- preview-template/index.ejs
This reverts commit 837d9a9eaa520f88af4cc6633a7e8857aac98a26.
> Revert "add "cc_exact_fit_screen" (#534)"

- assets/cases/ui/06.scrollview/scroll-view-bounce-back.scene
- assets/cases/ui/06.scrollview/scroll-view-bounce-back.ts
对应issue
https://github.com/cocos-creator/3d-tasks/issues/9834
将log赋值在label上可视化，方便非web调试用户查看log
> update scrollview bounce back testcase

- assets/cases/mipmapCheck/mipmapCheck.ts
RE：https://github.com/cocos-creator/3d-tasks/issues/9890
RE：https://github.com/cocos-creator/3d-tasks/issues/9842
> fix mipmap case bug when texture destroy

- assets/cases/event/system-event/dont-be-swallowed.ts
- assets/cases/event/system-event/dont-be-swallowed.ts.meta
- assets/cases/event/system-event/pointer-swallow.scene
- assets/cases/event/system-event/pointer-swallow.scene.meta
> 增加 pointer-swallow 测试例

- assets/cases/particle/particle-culling.scene
- assets/cases/particle/particle-trail2.scene
issue https://github.com/cocos-creator/3d-tasks/issues/9611
> Modify particle culling & particle trail 2

- assets/cases/camera/camera.scene
- assets/cases/mipmapCheck/mipMapMaterial.mtl
- assets/cases/rendertexture/targetTexture/use-render-texture-to-model.ts
- settings/v2/packages/builder.json
https://github.com/cocos-creator/3d-tasks/issues/9742
https://github.com/cocos-creator/3d-tasks/issues/8604
https://github.com/cocos-creator/3d-tasks/issues/9833
> restore camera clear flags

- assets/cases/network/NetworkCtrl.ts
减少意外情况的发生
* https://github.com/cocos-creator/3d-tasks/issues/9872
> Less time to justify timeout

- assets/cases/asset-bundle/test-bundle-zip/sub-scene.scene
- assets/cases/asset-bundle/test-bundle-zip/sub-scene.scene.meta
- assets/cases/asset-bundle/test-bundle/sub-scene.scene
- assets/cases/asset-bundle/test-bundle/sub-scene.scene.meta
resolve https://github.com/cocos-creator/3d-tasks/issues/7679
把 label 设为 shrink 模式，防止被裁剪
> fix sub-scene Label to shrink mode

- assets/cases/ui/other/uimodel/uimodel.scene
- assets/cases/ui/other/uimodel/uimodel.scene.meta
- settings/v2/packages/engine.json
Reverts cocos-creator/test-cases-3d#554
To Test autotest
> Revert "Fix ui blend issue on web"

- assets/cases/ui/other/uimodel/uimodel.scene
- assets/cases/ui/other/uimodel/uimodel.scene.meta
- settings/v2/packages/engine.json
Reverts cocos-creator/test-cases-3d#556
https://github.com/cocos-creator/3d-tasks/issues/6833
需要更新自动化测试效果图
> Revert "Revert "Fix ui blend issue on web""

- assets/cases/scripting/asset_loading/AssetLoading.scene
https://github.com/cocos-creator/3d-tasks/issues/10465
should clear depth buffer for the ui camera since there could be meshes present
> update camera clear flag

- assets/auto-test-config.json
- assets/cases/ui/02.label/label-spacing-x.meta
- assets/cases/ui/02.label/label-spacing-x/label-spacing-x.scene
- assets/cases/ui/02.label/label-spacing-x/label-spacing-x.scene.meta
- assets/cases/ui/02.label/label-spacing-x/labelSpacingXPrefab.prefab
- assets/cases/ui/02.label/label-spacing-x/labelSpacingXPrefab.prefab.meta
添加了labelspacingx的测试例，描述了测试步骤，需要在编辑器下进行操作测试。
> add labelspacingx testcase

- assets/auto-test-config.json
- assets/cases/ui/07.richtext/rich-text-long-string-truncation.meta
- assets/cases/ui/07.richtext/rich-text-long-string-truncation/rich-text-long-string-truncation.scene
- assets/cases/ui/07.richtext/rich-text-long-string-truncation/rich-text-long-string-truncation.scene.meta
Re: https://github.com/cocos-creator/3d-tasks/issues/10487
Changelog:
1. 添加了长字符串在richtext里的预切割的测试例
2. 将该场景加入自动化测试场景列表
> Rich text long string truncation

- assets/cases/event/system-event/dont-be-swallowed.ts.meta
- assets/cases/event/system-event/event-order.scene
- assets/cases/event/system-event/event-order.scene.meta
- assets/cases/event/system-event/event-order.ts
- assets/cases/event/system-event/event-order.ts.meta
- assets/cases/event/system-event/pointer-swallow.scene
changeLog:
- 优化事件穿透测试例
- 增加事件排序测试例
> optimize input test-case

- assets/cases/ui/24.motion-streak/motion-streak-ctrl.ts
- assets/cases/ui/24.motion-streak/motion-streak-ctrl.ts.meta
- assets/cases/ui/24.motion-streak/motion-streak.scene
- assets/cases/ui/24.motion-streak/motion-streak.scene.meta
Re： https://github.com/cocos-creator/3d-tasks/issues/11040
Re： https://github.com/cocos-creator/engine/pull/10055
> add motion-streak color change button

- assets/cases/ui/02.label/label-spacing-x/label-spacing-x.scene
- assets/cases/ui/02.label/label-spacing-x/labelSpacingXPrefab1.prefab
- assets/cases/ui/02.label/label-spacing-x/labelSpacingXPrefab1.prefab.meta
- assets/cases/ui/02.label/label-spacing-x/labelSpacingXPrefab2.prefab
- assets/cases/ui/02.label/label-spacing-x/labelSpacingXPrefab2.prefab.meta
优化了label-spacing-x的测试例，避免了编辑器操作步骤，直接对比修改前后的效果。
https://github.com/cocos-creator/3d-tasks/issues/10857
> optimize label-spacing-x test case

- assets/auto-test-config.json
- assets/cases/ui/02.label/fuzzy-text.meta
- assets/cases/ui/02.label/fuzzy-text/fuzzy-text.scene
- assets/cases/ui/02.label/fuzzy-text/fuzzy-text.scene.meta
关联issue: https://github.com/cocos-creator/3d-tasks/issues/11240
ChangeLog:
- 增加了fuzzyText的表现文本，并添加描述，使用不同版本对比测试
> add fuzzyText test case

- assets/cases/ui/07.richtext/rich-text-long-string-truncation.meta
- assets/cases/ui/07.richtext/rich-text-long-string-truncation/rich-text-long-string-truncation.scene
- assets/cases/ui/07.richtext/rich-text-long-string-truncation/rich-text-long-string-truncation.scene.meta
关联issue: https://github.com/cocos-creator/3d-tasks/issues/11241
ChangLog:
- 增加了中文和英文对比的效果，不同maxWdith对比的效果。以及QA同学可以通过不同版本对比。
> update split long string test case

- assets/auto-test-config.json
- assets/cases/single-compress/compressWithGray.scene
- assets/cases/single-compress/compressWithGray.scene.meta
- assets/cases/single-compress/compressWithGray.ts
- assets/cases/single-compress/compressWithGray.ts.meta
Re: https://github.com/cocos-creator/engine/pull/10129
Re: https://github.com/cocos-creator/3d-tasks/issues/11274
> Add compress texture with gray case

- settings/v2/packages/engine.json
Re: https://github.com/cocos-creator/3d-tasks/issues/11396
> remove useless flags in engine settings

- assets/cases/tween/script/TweenReadOnly.ts
> add tween node null condition

- assets/cases/dragonbones/DragonBonesAttach.scene
- assets/cases/dragonbones/DragonBonesAttach.scene.meta
- assets/cases/dragonbones/DragonBonesAttach.ts
- assets/cases/dragonbones/DragonBonesAttach.ts.meta
- assets/cases/dragonbones/DragonBonesCollider.scene
- assets/cases/dragonbones/DragonBonesCollider.scene.meta
- assets/cases/dragonbones/DragonBonesCollider.ts.meta
- assets/cases/spine/SpineAttach.scene
- assets/cases/spine/SpineAttach.scene.meta
- assets/cases/spine/SpineAttach.ts.meta
- assets/cases/spine/SpineCollider.scene
- assets/cases/spine/SpineCollider.scene.meta
- assets/cases/spine/SpineCollider.ts.meta
> modify test case for sockets of spine/dragonbones

- assets/cases/geometry-renderer/geometry-creator.ts
> geometry renderer refactor

- assets/cases/tween/scenes/tween-readonly.scene
- assets/cases/tween/script/TweenReadOnly.ts
(cherry picked from commit be2e725e06926f7e549ddd7f4064a6130d6358b5)
(cherry picked from commit 33e515254b9da3859ac745d9a343750f2aff43f2)
添加tween.stop，避免场景销毁后动画还在运行
> add tween.stop to finish dead tween-v3.5

- assets/cases/ui/07.richtext/rich-text-child-state.meta
- assets/cases/ui/07.richtext/rich-text-child-state/rich-text-child-state.scene
- assets/cases/ui/07.richtext/rich-text-child-state/rich-text-child-state.scene.meta
- assets/cases/ui/07.richtext/rich-text-child-state/rich-text-child-state.ts
- assets/cases/ui/07.richtext/rich-text-child-state/rich-text-child-state.ts.meta
https://github.com/cocos/3d-tasks/issues/11819
添加了richtext在被修改或隐藏显示后，子物体会被移除的问题的测试例。
> add richtext child state test case

- assets/cases/ui/07.richtext/rich-text-long-string-truncation/rich-text-long-string-truncation.scene
Re: https://github.com/cocos/3d-tasks/issues/11782
> fix rich text long string case touch bug

- assets/cases/ui/07.richtext/rich-text-child-state/rich-text-child-state.scene
- assets/cases/ui/07.richtext/rich-text-child-state/rich-text-child-state.scene.meta
Re:https://github.com/cocos/cocos-engine/pull/10700
Re:https://github.com/cocos/3d-tasks/issues/11819
> change Rich Text case to test children index bug

- assets/cases/geometry-renderer/geometry-creator.ts
- assets/cases/geometry-renderer/geometry-creator.ts.meta
- assets/cases/geometry-renderer/geometry-renderer.scene
- assets/cases/geometry-renderer/geometry-renderer.scene.meta
> add spline test case

- assets/auto-test-config.json
> fix auto-test json

- assets/cases/ui/02.label/vietnamese/vietnamese-show.scene
https://github.com/cocos/3d-tasks/issues/12316
add bg and its widget components, so that it will not be transparent
> Vietnamese bg #12316

- assets/cases/ui/21.video-player/video-player.scene
> add tips in video scene

- assets/cases/event/system-event/gamepad-event.scene
- assets/cases/event/system-event/gamepad-event.scene.meta
- assets/cases/event/system-event/gamepad-event.ts
- assets/cases/event/system-event/gamepad-event.ts.meta
> support gamepad event test case

- assets/auto-test-config.json
Re: https://github.com/cocos/3d-tasks/issues/12281
> add "terrain" scene

- assets/cases/TestList/ListItem.prefab
- assets/cases/TestList/TestList.scene
- assets/cases/TestList/backbutton.ts
- assets/cases/TestList/listitem.ts
- assets/cases/TestList/scenelist.ts
Optimize the problem that too many items in the test-list lead to low display efficiency on some platforms
> list items optimization

- assets/cases/scripting/build-time-constants-test/BuildTimeConstantsTest.ts
https://github.com/cocos/3d-tasks/issues/12006
> remove deprecated constants

- assets/cases/network/NetwrokDownload.ts
- assets/cases/network/NetwrokDownload.ts.meta
- assets/cases/network/network-download.scene
- assets/cases/network/network-download.scene.meta
https://github.com/cocos/cocos-engine/issues/11295
> add network-download testcase

- assets/cases/network/NetworkCtrl.ts
- assets/cases/network/NetworkDownload.ts
https://github.com/cocos/3d-tasks/issues/9071
https://github.com/cocos/3d-tasks/issues/12744
> refine networkCtrl&networkDownload

- assets/cases/audio/audioBuffer.scene
- assets/cases/audio/audioBuffer.scene.meta
- assets/cases/audio/audioBuffer.ts
- assets/cases/audio/audioBuffer.ts.meta
https://github.com/cocos/3d-tasks/issues/12482
> support audio buffer test cases

- assets/cases/dynamic-mesh/dynamic-mesh.ts
fix dynamic mesh async load issue
> fix dynamic mesh async load issue

- assets/cases/asset/test-bufferasset/TestBufferAsset.ts
https://github.com/cocos/3d-tasks/issues/13023
> Fix wrong result of TestBufferAsset , use a workaround function arrayBufferToHexString instead.

- assets/cases/event/acceleration/acceleration-event.ts
- assets/cases/event/event-first/event-first.ts
- assets/cases/event/event-info.ts
- assets/cases/event/multiTouch/MultiTouchCtrl.ts
- assets/cases/event/system-event/keyboard-event.scene
- assets/cases/event/system-event/keyboard-event.scene.meta
- assets/cases/event/system-event/keyboard-event.ts
- assets/cases/event/system-event/keyboard.png.meta
- assets/cases/event/system-event/mouse-event.ts
- assets/cases/event/system-event/touch-event.ts
- assets/cases/middleware/dragonbones/DragonBonesCtrl.ts
- assets/cases/middleware/tiled-map/puzzle.ts
- assets/cases/middleware/tiled-map/shield-node.ts
- assets/cases/scene/raycast/IntersectRayTest.ts
- assets/cases/scene/raycast/RaycastCanvasTest.ts
- assets/cases/scene/raycast/RaycastColliderTest.ts
- assets/cases/scene/raycast/RaycastModelTest.ts
- assets/cases/ui/08.mask/mask-inverted-event.ts
- assets/cases/ui/09.toggle/toggle-event-ctrl.ts
- assets/cases/ui/other/perspective-ui/ButtonScaler.ts
- assets/shared-res/first-person-camera.ts
- preview-template/index.ejs
https://github.com/cocos/3d-tasks/issues/12646
> remove deprecated systemEvent usage

- assets/cases/animation/scripts/MorphController.ts
- assets/migrate-canvas.ts
1. 新建节点不正常显示
2. morph-head场景不显示滚动条
https://github.com/cocos/3d-tasks/issues/13269
https://github.com/cocos/3d-tasks/issues/13291
> 修复编辑器预览相关问题

- assets/cases/localization-editor/script/ChangeLanguage.ts
- assets/cases/localization-editor/script/NewComponent.ts
Reverts cocos/cocos-test-projects#677
> Revert "Modify 修改l10n导入方式"

- assets/cases/localization-editor/script/ChangeLanguage.ts
- assets/cases/localization-editor/script/NewComponent.ts
This reverts commit 7a51df75bb2141d6f08240a53ec0984903d28410.
> Revert "Revert "[Optimize] Modify 修改l10n导入方式 (#677)" (#678)"

- assets/cases/localization-editor/scene/localization.scene
resolve https://github.com/cocos/3d-tasks/issues/13323
> change localization-editor Camera clear-flag to solid color

- assets/cases/ui/01.sprite/sprite-attribute-switch.meta
- assets/cases/ui/01.sprite/sprite-attribute-switch/SpriteAttributeSwitch.ts
- assets/cases/ui/01.sprite/sprite-attribute-switch/SpriteAttributeSwitch.ts.meta
- assets/cases/ui/01.sprite/sprite-attribute-switch/sprite-attribute-switch.scene
- assets/cases/ui/01.sprite/sprite-attribute-switch/sprite-attribute-switch.scene.meta
- assets/cases/ui/02.label/label-attribute-switch.meta
- assets/cases/ui/02.label/label-attribute-switch/LabelAttributeSwitch.ts
- assets/cases/ui/02.label/label-attribute-switch/LabelAttributeSwitch.ts.meta
- assets/cases/ui/02.label/label-attribute-switch/label-attribute-switch.scene
- assets/cases/ui/02.label/label-attribute-switch/label-attribute-switch.scene.meta
1. common attributes: active enabled contentSize color
2. sprite: spriteframe spriteType fillType
3. label: string horizontalalign verticalalign fontsize font useSystemFont overflow cachemode
add test case to test that any mistake occurs when switching these attributes
> sprite and label attributes switch test case

- assets/cases/ui/08.mask/mask-type-change.scene
- assets/cases/ui/08.mask/mask-type-change.ts
Re: https://github.com/cocos/cocos-engine/pull/12488
> mask type change with nesting

- assets/cases/scripting/build-time-constants-test/BuildTimeConstantsTest.ts
https://github.com/cocos/3d-tasks/issues/12646
https://github.com/cocos/3d-tasks/issues/12807
> [3.6.1] update number type of constant for NET_MODE

- assets/cases/ui/02.label/label-outline/label-outline.scene
- assets/cases/ui/02.label/label-shadow/label-shadow.scene
1. add tips aboud no-supporting platform
2. modify label contents
> fix outline and shadow bug

- assets/auto-test-config.json
- assets/cases/ui/02.label/label-cacheMode-color.scene
- assets/cases/ui/02.label/label-cacheMode-color.scene.meta
add label cache mode color test case
bmfont and ttf
> add label cache mode color test case
